site_name: 'Quix APIs'
site_description: 'Quix APIs'
site_author: 'Quix.io'
site_url: 'https://quix.io'

copyright: >
  Copyright &copy; 2020 - 2022 Quix –
  <a href="#__consent">Change cookie settings</a>

nav:
  - Intro: index.md
